=head1 Description

The SAS2RD macro produces an R .Rd file to document a SAS dataset
for an R package. It produces results similar to that of

  promptData()

in R but uses variable labels from the SAS dataset to make the .Rd
file more complete.

=head1 Usage

The SAS2RD macro is defined with keyword parameters.
The arguments may be listed within parentheses in any order, separated
by commas. For example: 

       %sas2rd();

=head2 Parameters

=over 4

=item DATA=

The name of the input data set [Default: C<DATA=_LAST_>]

=item LIBNAME=

Library name of input dataset [Default: C<LIBNAME=WORK>]

=item FILE=

Name of output .Rd file [Default: FILE=&DATA..RD]

=item VERBOSE=

Print variable names and labels?


=back 4

=head2 Examples

 %sas2rd(data=class, libname=sasuser);




